import { ROOMS, MESSAGE_TYPES } from './constants'
import { generateId } from './utils'

export function createDefaultRooms() {
  return ROOMS.map((r) => ({
    id: r.slug,
    slug: r.slug,
    name: r.name,
    description: r.description,
    created_at: new Date().toISOString(),
  }))
}

export function createWelcomeMessage(patronId) {
  return {
    id: generateId(),
    room_id: 'genel',
    user_id: patronId,
    text: 'Modulist HQ aktif. İş konuşmaları buradan yürütülecek.',
    type: MESSAGE_TYPES.DUYURU,
    mentions: [],
    pinned: true,
    reply_to_id: null,
    attachments: [],
    linked_record_type: null,
    linked_record_id: null,
    created_at: new Date().toISOString(),
  }
}

export function seedWorkspace(patronUser) {
  const rooms = createDefaultRooms()
  const messages = [createWelcomeMessage(patronUser.id)]
  return {
    users: [patronUser],
    rooms,
    messages,
    tasks: [],
    companies: [],
    bugs: [],
    campaigns: [],
    contents: [],
    finance: [],
    feedback: [],
    dailyMetrics: [],
    dmThreads: [],
    notifications: [],
    settings: { darkMode: false, activeCustomerCount: 0, estimatedMrr: 0 },
    initialized: true,
  }
}

export function loadSampleData(data, patronId) {
  const now = new Date()
  const companies = [
    {
      id: generateId(),
      ad: 'Atlas Emlak',
      sektor: 'emlak',
      yetkili: 'Mehmet Yılmaz',
      telefon: '0532 111 2233',
      email: 'mehmet@atlasmak.com',
      kaynak: 'referans',
      sorumlu_id: null,
      pipeline: 'trial',
      demo_tarihi: null,
      demo_saati: null,
      trial_baslangic: new Date(now - 25 * 86400000).toISOString().split('T')[0],
      trial_bitis: new Date(now.getTime() + 2 * 86400000).toISOString().split('T')[0],
      paket: 'profesyonel',
      aylik_tutar: 4500,
      dekont_durumu: 'bekliyor',
      modulist_tenant_acildi: false,
      modulist_email: null,
      kayip_nedeni: null,
      notlar: 'Trial bitiyor, takip gerekli.',
      created_at: new Date(now - 30 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: generateId(),
      ad: 'YapıPro İnşaat',
      sektor: 'yapsat',
      yetkili: 'Ayşe Kaya',
      telefon: '0533 444 5566',
      email: 'ayse@yapipro.com',
      kaynak: 'fuar',
      sorumlu_id: null,
      pipeline: 'demo',
      demo_tarihi: now.toISOString().split('T')[0],
      demo_saati: '14:00',
      trial_baslangic: null,
      trial_bitis: null,
      paket: 'kurumsal',
      aylik_tutar: 8500,
      dekont_durumu: 'yok',
      modulist_tenant_acildi: false,
      modulist_email: null,
      kayip_nedeni: null,
      notlar: '',
      created_at: new Date(now - 10 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: generateId(),
      ad: 'Nova Gayrimenkul',
      sektor: 'ikisi',
      yetkili: 'Can Demir',
      telefon: '0535 777 8899',
      email: 'can@novagm.com',
      kaynak: 'google',
      sorumlu_id: null,
      pipeline: 'musteri',
      demo_tarihi: null,
      demo_saati: null,
      trial_baslangic: null,
      trial_bitis: null,
      paket: 'baslangic',
      aylik_tutar: 2500,
      dekont_durumu: 'onaylandi',
      modulist_tenant_acildi: true,
      modulist_email: 'can@novagm.com',
      kayip_nedeni: null,
      notlar: 'Aktif müşteri',
      created_at: new Date(now - 60 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ]

  const bugs = [
    {
      id: generateId(),
      baslik: 'PDF export bozuk',
      aciklama: 'Bazı raporlarda PDF çıktısı eksik sayfa veriyor.',
      kaynak: 'musteri',
      sektor: 'emlak',
      oncelik: 'kritik',
      durum: 'acik',
      modulist_referans: 'BUG-1042',
      sorumlu_id: null,
      iliskili_firma_id: companies[0].id,
      created_at: new Date(now - 3 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: generateId(),
      baslik: 'Mobil bildirim gecikmesi',
      aciklama: 'Push bildirimler 5-10 dk gecikmeli geliyor.',
      kaynak: 'ic_bulgu',
      sektor: 'genel',
      oncelik: 'yuksek',
      durum: 'devam',
      modulist_referans: 'BUG-1038',
      sorumlu_id: null,
      iliskili_firma_id: null,
      created_at: new Date(now - 7 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ]

  const extraMessages = [
    {
      id: generateId(),
      room_id: 'satis',
      user_id: patronId,
      text: 'Atlas Emlak trial bitiyor, @ekip takip edelim.',
      type: MESSAGE_TYPES.NORMAL,
      mentions: [],
      pinned: false,
      reply_to_id: null,
      attachments: [],
      linked_record_type: 'firma',
      linked_record_id: companies[0].id,
      created_at: new Date(now - 2 * 3600000).toISOString(),
    },
    {
      id: generateId(),
      room_id: 'satis',
      user_id: patronId,
      text: 'YapıPro demo bugün 14:00 — hazırlık tamam mı?',
      type: MESSAGE_TYPES.NORMAL,
      mentions: [],
      pinned: false,
      reply_to_id: null,
      attachments: [],
      linked_record_type: 'firma',
      linked_record_id: companies[1].id,
      created_at: new Date(now - 5 * 3600000).toISOString(),
    },
    {
      id: generateId(),
      room_id: 'urun',
      user_id: patronId,
      text: 'PDF export bug kritik — öncelik verelim.',
      type: MESSAGE_TYPES.KARAR,
      mentions: [],
      pinned: true,
      reply_to_id: null,
      attachments: [],
      linked_record_type: 'bug',
      linked_record_id: bugs[0].id,
      created_at: new Date(now - 1 * 86400000).toISOString(),
    },
    {
      id: generateId(),
      room_id: 'genel',
      user_id: patronId,
      text: 'Haftalık toplantı Cuma 10:00.',
      type: MESSAGE_TYPES.DUYURU,
      mentions: [],
      pinned: false,
      reply_to_id: null,
      attachments: [],
      linked_record_type: null,
      linked_record_id: null,
      created_at: new Date(now - 4 * 86400000).toISOString(),
    },
    {
      id: generateId(),
      room_id: 'buyume',
      user_id: patronId,
      text: 'Mart reels kampanyası planı hazır.',
      type: MESSAGE_TYPES.NORMAL,
      mentions: [],
      pinned: false,
      reply_to_id: null,
      attachments: [],
      linked_record_type: null,
      linked_record_id: null,
      created_at: new Date(now - 6 * 86400000).toISOString(),
    },
  ]

  const campaigns = [
    {
      id: generateId(),
      ad: 'Mart Meta Kampanyası',
      kanal: 'Meta',
      donem_baslangic: new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0],
      donem_bitis: new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().split('T')[0],
      butce_plan: 15000,
      butce_harcanan: 11200,
      tiklama: 4200,
      kayit_sayisi: 28,
      notlar: 'Emlak segmenti',
      created_at: new Date().toISOString(),
    },
    {
      id: generateId(),
      ad: 'Google Search Q1',
      kanal: 'Google',
      donem_baslangic: new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0],
      donem_bitis: new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().split('T')[0],
      butce_plan: 8000,
      butce_harcanan: 5400,
      tiklama: 1800,
      kayit_sayisi: 12,
      notlar: '',
      created_at: new Date().toISOString(),
    },
  ]

  const feedback = [
    {
      id: generateId(),
      tip: 'sikayet',
      metin: 'Rapor indirme yavaş çalışıyor.',
      firma_id: companies[0].id,
      kaynak: 'telefon',
      durum: 'inceleniyor',
      sorumlu_id: patronId,
      created_at: new Date(now - 2 * 86400000).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ]

  const dailyMetrics = [
    {
      id: generateId(),
      user_id: patronId,
      tarih: now.toISOString().split('T')[0],
      arama_sayisi: 15,
      ulasilan: 8,
      demo_ayarlanan: 2,
      takip_aramasi: 5,
      notlar: 'Örnek gün',
      created_at: new Date().toISOString(),
    },
  ]

  const finance = [
    {
      id: generateId(),
      tip: 'gider',
      kategori: 'reklam',
      tutar: 3500,
      aciklama: 'Meta reklam ödemesi',
      kampanya_id: campaigns[0].id,
      tarih: now.toISOString().split('T')[0],
      durum: 'bekliyor',
      giren_id: patronId,
      created_at: new Date().toISOString(),
    },
  ]

  return {
    ...data,
    companies,
    bugs: bugs.map((b) => ({ ...b, bildiren_id: patronId })),
    campaigns,
    feedback,
    dailyMetrics,
    finance,
    messages: [...data.messages, ...extraMessages],
  }
}
